// <auto-generated />
using FaerieTables.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FaerieTables.Api.Migrations
{
    [DbContext(typeof(RandomTableContext))]
    partial class RandomTableContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");
#pragma warning restore 612, 618
        }
    }
}
